IS-99 Added TC:IS-99 Teklif Haklarimda Aktif haklar
ExampleGuys/ismakinesiUI pull request #16
Opened 2023-01-27 23:12 UTC by ilknurDaglar

2023-01-27 23:16 UTC, seylab requested changes

2023-01-27 23:16 UTC, seylab commented on src/test/resources/features/006_KullaniciHaklari/TeklifHakki.feature
> +    Then kullanici  kullanilabilir durumdaki teklif haklarini gorur
aynı senaryo 2 kez mi yazılmış?

2023-01-27 23:23 UTC, seylab requested changes

2023-01-27 23:23 UTC, seylab commented on src/test/resources/features/006_KullaniciHaklari/TeklifHakki.feature
> +    Then kullanici  kullanilabilir durumdaki teklif haklarini gorur
**1. satırda feature için isim yazılmalı. ve feature dan önce bir tag eklenmeli. @login, @teklifHakki, @smoke, @regression benzeri**

2023-01-27 23:36 UTC, ilknurDaglar commented on src/test/resources/features/006_KullaniciHaklari/TeklifHakki.feature
> +    Then kullanici  kullanilabilir durumdaki teklif haklarini gorur
Evet birini silebilirsiniz. İki defa göndermeye calistim İS-99 u  iki defa features yazmış diğer classlarda tek defa yazilmis

2023-01-28 06:42 UTC, seylab approved these changes

2023-01-28 06:46 UTC, merged