IS-354 Added TC:IS-354 Ana Sayfadan Instagram Hesabina Gitme
ExampleGuys/ismakinesiUI pull request #21
Opened 2023-01-28 17:44 UTC by sirinkapzan

2023-01-28 19:41 UTC, mudadagli approved these changes

2023-01-28 20:42 UTC, seylab requested changes

2023-01-28 20:42 UTC, seylab commented on src/test/resources/features/001_Login-Register/Login.feature
> +
Boş satırları silebilir miyiz

2023-01-28 20:42 UTC, seylab commented on src/test/java/com/ismakinesi/pages/LoginPage.java
> +
Boş satırları silebilir miyiz

2023-01-28 20:42 UTC, seylab commented on src/test/java/com/ismakinesi/pages/LoginPage.java
> +
Boş satırları silebilir miyiz

2023-01-28 20:42 UTC, seylab commented on src/test/java/com/ismakinesi/stepDefinitions/LoginStepDefs.java
> +
Boş satırları silebilir miyiz

2023-01-29 18:12 UTC, seylab approved these changes

2023-01-29 18:44 UTC, merged